kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: build-test2
  namespace: build-test
  labels:
    build: build-test2
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 10.168.0.76:9000/dev-registry/helloworld-test:latest
    pushSecret:
      name: nexus-secret
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: build-test
        name: 'golang:alpine'
  postCommit: {}
  source:
    type: Git
    git:
      url: 'https://github.com/VikneshSuresh/build-test'
  runPolicy: Serial
